### ISSUE TITLE
Discourse Setup

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-community#1]
Setup OSLC Community [Discourse](http://discourse.org/) instance.

Preference to have them live on sub-domains:
discourse.open-services.net

2 Options:

1. Self-hosting
https://meta.discourse.org/t/running-other-websites-on-the-same-machine-as-discourse/17247

2. Paid hosting

Things to consider:

1. Cost
2. Features being offered for each, e.g. email configuration
3. Install process
4. Path to upgrades + maintenance

**TODO**

- [ ] Set up https

- [ ] Enable registration via Github

**Comment by brianking** [comment]
We've setup a Digital Ocean droplet and will install Discourse there.

**Comment by brianking** [comment]
I like how Feverbee integrates Discourse into their site.

1. Go to https://www.feverbee.com/
2. Select Community from the top menu, which leads you to https://experts.feverbee.com/

Note:
* Prominent Search at the top
* Popular Topics section
* A couple of other sections before it starts to list latest posts

We may not necessarily need all these, but what I like the most and think we should do is have it on a subdomain and to keep the main site navigation structure and theme colours as much as possible.

**Comment by brianking** [comment]
I have http://discourse.oslc.co setup now. It is not open for new users yet, while we set it up properly and seed it with some topics, i.e. invite only.

For email/SMTP, we are using [Mailgun](https://www.mailgun.com) which has a monthly free allocation of 10,000 emails.

**Comment by berezovskyi** [comment]
Tried to sign up with GH:

![image](https://user-images.githubusercontent.com/64734/28462821-4e29e47a-6e1d-11e7-9505-1732c36588c0.png)

**Comment by brianking** [comment]
@berezovskyi Please try again. 

I made the following changes:

"Public registration is disabled, all new users must be explicitly invited by staff." - DISABLED

"Staff must approve all new user accounts before they are allowed to access the site. WARNING: enabling this for a live site will revoke access for existing non-staff users!" - ENABLED

**Comment by berezovskyi** [comment]
thanks @brianking 

there is still a URI mismatch:

<img width="1016" alt="screen shot 2017-10-07 at 19 37 00" src="https://user-images.githubusercontent.com/64734/31310344-e934693e-ab96-11e7-9e21-4b877a8868c9.png">

**Comment by brianking** [comment]
@berezovskyi Github signup should be working now. Let us know.

**Comment by berezovskyi** [comment]
Nope, still not working after shift-refresh:

<img width="1552" alt="pasted_image_2017-10-13__15_37" src="https://user-images.githubusercontent.com/64734/31548924-cc9acf80-b02c-11e7-872a-52d551e64161.png">

I think the port number is causing this problem. Note that I am using the sign-up button, not the login.

**Comment by brianking** [comment]
FYI we are tracking this in issue #15

**Comment by berezovskyi** [comment]
My apologies

**Comment by brianking** [comment]
As this is setup and we are tracking the github issue in #15 I am closing this one.
